### ISSUE TITLE
Longpolling

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/wreck#103]
Is there a way to do long polling with wreck?

**Comment by mtharrison** [comment]
I don't see why not. You'd have to implement it yourself though. Set a long timeout on requests and let the server hold onto it until there's some response. Then fire off another wreck request immediately on response/timeout.

**Comment by AdriVanHoudt** [comment]
it seems the standard is infinite wait so let me look further into it, thanks for the repoll tip

**Comment by AdriVanHoudt** [comment]
ok so it works as expected, just need to repoll
