### ISSUE TITLE
Allowing of mixed capitalization

### ISSUE THREAD

**Issue by danielb2** [hapijs/wreck#107]
Due to javascript not guaranteeing order of keys, and RFI for headers being case-insensitive, it's possible to have a random result when sending headers.

For example, in production we had bad capitalization of the `cookie` header using `Cookie` and `cookie`.
One was chosen at random it appears causing intermittent errors.

What are thoughts on validating the headers to only allow one capitalization variation?

**Comment by hueniverse** [comment]
Not a good idea. There are known bad servers out there with specific capitalization requirements (e.g. Yahoo requires Authorization for OAuth).

**Comment by danielb2** [comment]
My suggestion isn't disallowing any specific capitalization but rather just throwing an error of multiple ones exist.

For example:  var obj = { cookie: '...', Cookie: '...' };  would raise an error to the effect of "Multiple headers of the same name passed. Please pick one capitalization"

**Comment by geek** [comment]
I would rather that be enforced outside of wreck, prior to trying to make a request.  I can see the value in adding it in, but it really is going to just complicate the common case.

**Comment by danielb2** [comment]
OK, just one more comment, because we were using h2o2 for proxy, this was difficult to track down. The people who wrote the initial proxying didn't realize the capitalization mattered (I suspect). We found it only because we ended up snooping traffic using wireshark and the SSL keys.

**Comment by hueniverse** [comment]
I would argue this is a node level issue, where it allows you to set the same header with different caps.

**Comment by danielb2** [comment]
That's a fair argument. I'll bring it up there
