### ISSUE TITLE
Response Event

### ISSUE THREAD

**Issue by arb** [hapijs/wreck#111]
At present, wreck emits a "response" event when the upstream results comes back. This is fine if you're only using a single instance of wreck. If you use h2o2 and good and your own hapi JS code, the different versions make this event basically impossible to use. The user has to make sure the versions of everything are all the same plus it doesn't work at all if you use `wreck.defaults`.

I think we need to find a better solution to this problem. Emit the event on a global event emitter perhaps? Make packages that use wreck pass it in somewhere as a parameter so everything uses the same instance?

https://github.com/hapijs/good/pull/386
https://github.com/hapijs/good/pull/367
https://github.com/hapijs/good/pull/333

**Comment by geek** [comment]
I support this move, now with ES6 support maybe we can come up with a better solution.

**Comment by arb** [comment]
There is also [this](https://github.com/hapijs/good/issues/402#issuecomment-155859532) idea; low level logging down at the http/https layer. At the end of the day, and request module is going to use core http or https.

**Comment by arb** [comment]
Something like this - https://github.com/meetearnest/global-request-logger

**Comment by geek** [comment]
@arb do you have any other ideas other than the monkey patch solution?  I am not seeing anything better than what we have.  Is there a reason that you have multiple wreck versions in the same process?

**Comment by arb** [comment]
Emitting the an event on `process` rather than on `wreck` directly. It's super easy to get multiple versions of wreck in the same process. If you're using h2o2 + good + your own code... it's super easy to end up with even patch version differences.
