### ISSUE TITLE
use of es6 prevents use in browsers (let, const, ()=> )

### ISSUE THREAD

**Issue by jasonswearingen** [hapijs/wreck#112]
The Hapi ecosystem is great!   and using Browserify, we can even use Wreck inside a webbrowser.

Unfortunately, Wreck (and other 1st party hapi plugins) tend to use ES6 keywords such as let, const, and lambda functions.   While these work in "modern" browsers like Chrome, This greatly decreases the browser compatibility   (Does not work in IE or safari)

Is there an easy way to get this compatibility in?   I know browsers are not the intended target, but it seems with slight changes, it would work great.     

FYI I have tried using Babel to transpile Wreck and it's dependencies to ES5 but there are a bunch of problems with this approach (granted I"m a babel novice so might be my fault I can't really get it working)

**Comment by hueniverse** [comment]
The short answer is no. There is a longer debate on this in the hapijs/discuss repo.

**Comment by devinivy** [comment]
If you're referencing the chat in contrib, that's here: https://github.com/hapijs/contrib/issues/67

**Comment by jasonswearingen** [comment]
thanks, for both  the discuss / contrib links :)

**Comment by jasonswearingen** [comment]
If anyone wants to get hapi utils working in the browser, here's a high-level on how I got Wreck to work:

1) Use Browserify (obvious?)
2) Use the Closure Compiler, you can set it's options to not do any minification, just doing ES6 to ES5 translation.  it works great.  (Using it via gulp, the https://www.npmjs.com/package/gulp-closure-compiler module)

Note, I originally tried using Babel instead of Closure Compiler, but Babel takes a long time to run and it's resulting output of some of the Wreck dependencies end up with syntax errors somehow (debugging it's output is difficult).  Switching to the closure compiler worked on the first try.  Also, can use this as a minification step too.

note that you don't need closure compiler to work in Chrome, but as Wreck/other hapi utils use ES6 code, it won't work in IE (or Safari I think).   using closure for transpilation to ES5 makes it work (down to IE9 at least)
