### ISSUE TITLE
Suggestion: Allow json objects as payload 

### ISSUE THREAD

**Issue by n321203** [hapijs/wreck#113]
Wreck supports strings, buffers and streams as payload when doing a post/put/patch. I would suggest adding support for JSON objects, just because it would be beautiful to be able to write

`Wreck.post("/endpoint", {payload: {"some":"data"}}, callback)`

Maybe implemented by calling `JSON.stringify()` on the payload if `typeof payload == "object"` (which would include arrays as well) and set the application/json header.

Just an idea.

**Comment by hueniverse** [comment]
wreck was designed to be small and simple. At some point you end up with **request**.

**Comment by geek** [comment]
@n321203 this is a common use case and I like the idea.  I am happy to accept a PR for this with stringify.  I just hope we don't end up with bugs from throws when people try to stringify objects with circular references, then we will end up needing something like safe stringify.  We will want to make it clear in the documentation that we aren't doing anything to prevent the throw... and I would prefer to avoid adding another dependency.
