### ISSUE TITLE
h2o2 use

### ISSUE THREAD

**Issue by jhawlwut** [hapijs/wreck#116]
I have a use case where I'm using h2o2 to proxy to an API with SSL enabled, mostly for the UI to be able to interact with it. I manually set the cookie to localhost's domain and it passes through okay using "passThrough" set to true. Using postman or the browser, the cookie is correctly passed through state and all is well through the direct proxied route.

I'm using wreck to make a few calls before the server loads the base route ("/") - I tried just calling the local h2o2 proxy route, but it appears the domain isn't getting set to pull the cookie from. The same occurs when I just try to call the external API directly with "rejectUnauthorized" set to false.

```json
domain: 
Domain {
domain: null

```

Also, state appears to be empty which I'm guessing is due to the domain not being passed to grab the cookie from localhost?

Any ideas how to get this going? Or am I trying to do something that just isn't possible?

My wreck code basically looks like this:
```javascript
let options = {
 baseUrl: 'http://localhost:9999',
 rejectUnauthorized: false,
 json: true
};
wreck.request('get', '/v1/ui/test', options, function (err, res) {
 console.log(res);
 wreck.read(res, {json:true}, function (err, body) {
   reply(body);
 });
});
```
Where "baseUrl" is interchangeable with the direct API route vs localhost

**Comment by geek** [comment]
@jhawlwut sorry for the long delay in getting a response to you :/

Are you trying to read the cookies from localhost?  You should be able to grab the value of the cookie header, you may need to change the value of domain, as you said though.  

If you need to set the cookie, you can set the cookie header value:

```js
let options = {
  baseUrl: 'http://localhost:9999',
  rejectUnauthorized: false,
  json: true,
  headers: {
    Cookie: 'name=value;'
  }
};
```

**Comment by geek** [comment]
@jhawlwut please reopen if this is still an issue
