### ISSUE TITLE
Request - built-in handling of x-ww-form-urlencoded POST payloads?

### ISSUE THREAD

**Issue by mattboutet** [hapijs/wreck#122]
Unless I've missed something, POST'ing to endpoints that require this content-type requires jumping through hoops to correctly encode your payload.

It seems like it would be helpful if it was possible to pass in an object or some JSON and have it encoded for you.  I'm not quite sure how the mechanics of this would work, but implementing it wouldn't be _that_ hard.

If there's interest, I'd be happy to try to put together a pull request.

**Comment by mtharrison** [comment]
Wreck purposefully doesn't give you all the bells and whistles you get with something like [request](https://www.npmjs.com/package/request). It just expects your payload to be a string, Buffer or stream and doesn't concern itself with encoding.

It's fairly trivial though to encode your payload and pass along the right header:

### application/x-www-form-urlencoded
```javascript
const Wreck = require('wreck');
const Querystring = require('querystring');  // built-in module

const myPayload = {
    name: 'John Doe',
    age: 42
};

Wreck.post('http://localhost:4000/', {
    payload: Querystring.stringify(myPayload),
    headers: {
        'content-type': 'application/x-www-form-urlencoded'
    }
}, (err, res, payload) => {

    ...
});
```

### application/json
```javascript
const Wreck = require('wreck');

const myPayload = {
    name: 'John Doe',
    age: 42
};

Wreck.post('http://localhost:4000/', {
    payload: JSON.stringify(myPayload),
    headers: {
        'content-type': 'application/json'
    }
}, (err, res, payload) => {

    ...
});
```

There are good npm packages for working with multipart forms too and probably any other encoding. I don't think this is something Wreck should concern itself with. Just my 2 cents.

**Comment by geek** [comment]
@mattboutet I am open to supporting application/json, since we do support it on the response.

**Comment by mattboutet** [comment]
@geek - `application/json` is quite a bit simpler than `application/x-www-form-urlencoded`, so I don't see that addition as quite as helpful.

Maybe a `content-type` property under `option`?  I'd be happy to try adding that with support for both `application/json` and `application/x-www-form-urlencoded'. Thoughts?

**Comment by geek** [comment]
@mattboutet you can set the headers already.... not sure on a separate option.

**Comment by mattboutet** [comment]
@geek - true, that's what I'm doing now.  I was just trying to think of a convenient way to tell Wreck what (if anything) it should do with the payload.  If I just relied on what was set via `content-type` in the headers to signal how it should handle `payload`, then it'd break backwards compatibility, but with a new flag we don't have to worry about that.

**Comment by hueniverse** [comment]
I would rather we keep wreck simple. JSON stringify/parsing is reasonable but form encoding goes too far.

**Comment by geek** [comment]
@hueniverse agreed... I don't want to introduce another dependency either.  `application/json` is reasonable, but as you said @mattboutet, it may not be useful.

**Comment by mtharrison** [comment]
Allowing `payload` to be an object and implicitly setting the content-type header to `application/json` sounds like a useful addition to Wreck and a kind of compromise to this issue. As an added bonus it will align Wreck more closely with how [Shot works](https://github.com/hapijs/shot/blob/master/lib/request.js#L64-L70) too.

**Comment by nlf** [comment]
i agree that form encoding is too far, and since that's the original request in this issue it should probably be closed.

making the json support a little fancier could be a new issue, though. i'll let @geek decide on that one.
