### ISSUE TITLE
RSA Keys Hardcoded into the code base. 

### ISSUE THREAD

**Issue by sysv** [hapijs/wreck#124]
There are a bunch of RSA private keys hardcoded into your src code base. Discovered this in some borrowed code. Could you kindly remove them and/or code key gen into the TEST. I think you'd want to do that anyway since your TLS or SSH private keys are world exposed. File paths and line no. are as follows: 

./good/test/fixtures/server.key:1:-----BEGIN RSA PRIVATE KEY-----
./good/test/fixtures/server.key:27:-----END RSA PRIVATE KEY-----
./hapi/test/connection.js:187:            key: '-----BEGIN RSA PRIVATE KEY-----
./hapi/test/connection.js:380:                key: '-----BEGIN RSA PRIVATE KEY-----
./hapi/test/transmit.js:1633:                    key: '-----BEGIN RSA PRIVATE KEY-----
./wreck/test/index.js:267:            key: '-----BEGIN RSA PRIVATE KEY-----
./wreck/test/index.js:292:            key: '-----BEGIN RSA PRIVATE KEY-----
./wreck/test/index.js:317:            key: '-----BEGIN RSA PRIVATE KEY-----
./wreck/test/index.js:451:            key: '-----BEGIN RSA PRIVATE KEY-----

**Comment by Marsup** [comment]
Who cares, it's for test purposes.

**Comment by sysv** [comment]
Because people import the code en whole and also test with real data.

**Comment by Marsup** [comment]
It's not used by the library itself, if you copy/paste source code from the tests without understanding what you're doing, that's kind of your fault.

**Comment by Marsup** [comment]
@geek another opinion on that matter ? Took it on me to answer but you might disagree.

**Comment by sysv** [comment]
I agree it seems small from code literal perspective, it's less about the code itself and more about operational use when code in re-use and deployments... And my dev guys will likely keep importing version after version here

**Comment by hueniverse** [comment]
I think this is silly but if someone wanted to spend the time on generating the keys in run-time, I would support merging it.

**Comment by geek** [comment]
> And my dev guys will likely keep importing version after version here

@sysv importing where?  You can remove test folders in your builds.
