### ISSUE TITLE
Mistake in manual

### ISSUE THREAD

**Issue by indreek** [hapijs/wreck#151]
Hi

```js
const Wreck = require('wreck');

Wreck.post('https://posttestserver.com/post.php', { payload: { hello: 'post' } }, (err, res, payload) => {
    /* do stuff */
});
```

this gives me error 

> Error: Uncaught error: options.payload must be a string, a Buffer, or a Stream

Am i doing something wrong or there is a mistake in manual?

Indrek

**Comment by Marsup** [comment]
You're probably using an old version and using github as documentation, you shouldn't. Or at least use the matching version on github.

**Comment by indreek** [comment]
Im using this link: https://github.com/hapijs/wreck/blob/master/README.md

**Comment by Marsup** [comment]
This is the development branch, which version of wreck are you using ?

**Comment by indreek** [comment]
Im using 10, but i got it working. Just saw the mistake in manual. Where is the live branch?

**Comment by Marsup** [comment]
Your error looks exactly like a wreck 8 error, not 10. If you really found an error in the docs feel free to do a PR though.

**Comment by indreek** [comment]
Can you pass me the latest documentation link?

**Comment by Marsup** [comment]
https://github.com/hapijs/wreck/blob/v10.0.0/README.md

**Comment by indreek** [comment]
Yes, it's same as my posted link. Here is a fixed doc.

https://github.com/indreek/wreck

**Comment by Marsup** [comment]
This is not a fix, this is what wreck already does (https://github.com/hapijs/wreck/blob/master/lib/index.js#L121). Looking at your error, I can pretty much guarantee you're not using version 10, please check again.

**Comment by geek** [comment]
@indreek please verify that the wreck module you are requiring is v10
