### ISSUE TITLE
Question. What is the equivalent of curl -u

### ISSUE THREAD

**Issue by no-more** [hapijs/wreck#152]
Hi, I couldn't find out how to a curl command like this one : `curl -X POST -u "client_id:secret"` with wreck.

Could someone help me please.

Thanks a lot.

**Comment by mtharrison** [comment]
I assume this is for Basic HTTP auth? You can just build the authorization header:

```js
const Wreck = require('wreck');

const options = { 
    headers: { 
        authorization: `Basic ${new Buffer('client_id:secret').toString('base64')}` 
    } 
};

Wreck.post('https://example.com', option, (err, res, payload) => {
   ...
});
```

**Comment by no-more** [comment]
Hi,

Thanks, but I didn't manage to make this work. I don't know much about the -u option in curl which is used to send USER:PASSWORD. Are you sure it's converted to an authorization header ?

I'll try to find more information.

Thanks.

**Comment by mtharrison** [comment]
Yes, that's how it works. See below

![screen shot 2016-10-17 at 10 00 00](https://cloud.githubusercontent.com/assets/916064/19431530/b7eee10a-9450-11e6-86c9-916257526a5f.png)
