### ISSUE TITLE
Question about responses as readable streams

### ISSUE THREAD

**Issue by ryanwilliamquinn** [hapijs/wreck#153]
If I use Wreck.request, I can pipe the response, and the text is dumped out to my terminal.
```
Wreck.request('GET', 'https://github.com/hapijs/wreck', {}, (err, res) => {
  res.pipe(process.stdout)
})
```

If I use Wreck.get, no text is dumped to my terminal. I think this is because this uses Wreck.read internally, and the readstream already emitted its 'finish' event. Is there a way to re-start the readstream from the beginning? Otherwise, what is the point of documenting that the response is a readable stream in this case?
```
Wreck.get('https://github.com/hapijs/wreck', {}, (err, res) => {
  res.pipe(process.stdout)
})
```

**Comment by devinivy** [comment]
I believe that you are right about it being already-read.  Its contents get funneled into a third `payload` callback argument that isn't shown in your example code.  In this case I agree that the docs stating `res` is a readable stream is a bit of a "red herring," though correct.

**Comment by ryanwilliamquinn** [comment]
I wonder how that can be improved? It did cost me some time trying to understand why I couldn't pipe anything from the response stream.

**Comment by hueniverse** [comment]
It just need to state that it is a "used-up" stream and that you cannot pipe it.
