### ISSUE TITLE
Losing error body

### ISSUE THREAD

**Issue by irothschild** [hapijs/wreck#166]
I'm using Wreck.request() to proxy a call to an API server (similar to h2o2.) When the response is a 400 Bad Request, wreck calls `req.abort()` in `finish` and I'm unable to read the response body. Is this the intended behaviour?

**Comment by irothschild** [comment]
I was using wreck 11.0.0. Apparently fixed in wreck 12.0.0.

**Comment by croeber** [comment]
Can you please explain to me how this fixed in 12.0? As far as I can see is that the request is still abort and/or there is no response body. I need the response body for a 400.
