### ISSUE TITLE
Retry request when network error?

### ISSUE THREAD

**Issue by danactive** [hapijs/wreck#171]
I am using wreck to pass critical data to a service with 99.5 % availability, approximately 5 out of every 1,000 requests will fail. Ideally failed requests will be retried to improve the delivery success rate. Does wreck support retries with a delay and attempt count? If not, please post some tips as I don't want to swap wreck for another module.

**Comment by devinivy** [comment]
Wreck doesn't support retries, but you can pull-in this functionality in a general-purpose way using something like [node-backoff](https://github.com/MathieuTurcotte/node-backoff).

**Comment by nitinsh99** [comment]
@devinivy would you guys be willing to accept PRs to add retry functionality?

**Comment by devinivy** [comment]
I can't speak to that definitively, but my expectation is that it's still desired to keep wreck minimal.  Luckily I don't think this functionality would rely on any wreck internals, so you can compose retry logic directly on top of wreck.

**Comment by nitinsh99** [comment]
> so you can compose retry logic directly on top of wreck.

I did that.. was just hoping to port this over to the main repo so I don't have to hack locally and others can use this as well..hence the question..

**Comment by hueniverse** [comment]
@nitinsh99 retried do not belong in wreck. It's a higher level functionality.
