### ISSUE TITLE
Content-Type not passing the regular expression for JSON smart parse

### ISSUE THREAD

**Issue by osukaa** [hapijs/wreck#176]
Hi, 

I have a problem where contentful is returning me a `Content-Type: application/vnd.contentful.delivery.v1+json` but the regex doesn't pass and `wreck.read` returns the buffer instead of parsing it. `json: force` does the trick, but I think the regex should be updated. :)

https://regex101.com/r/ZX6nwW/1

**Comment by AdriVanHoudt** [comment]
Adding 0-9 should work `^application\/[a-z0-9.+-]*json$` but I do not know if it could break anything, on a hunch I would say it is fine

**Comment by arb** [comment]
I think this is why `force` was added... to deal with atypical content-type headers.

**Comment by geek** [comment]
@AdriVanHoudt @osukaa json is json, feel free to PR the update
