### ISSUE TITLE
wrong content-length on post causes request to hang

### ISSUE THREAD

**Issue by xjamundx** [hapijs/wreck#178]
I don't really know what the expected behavior is here, but we ran into an issue at PayPal where we tried to forward headers from a request to another and when the old `content-length` was passed the request hung for a very long time (usually triggering a timeout). This can be easily repro'd:

```js
require('wreck').post('https://posttestserver.com/post.php', {
    headers: { 'content-length': 123 },
    payload: JSON.stringify({ hello: 'post' })
}, (err, res, payload) => {
    if (err) console.warn(err);
    console.log(payload.toString())
})
```

If you run the exact same call without the `content-length` header it will return immediately with a response.

```js
require('wreck').post('https://posttestserver.com/post.php', {
    payload: JSON.stringify({ hello: 'post' })
}, (err, res, payload) => {
    if (err) console.warn(err);
    console.log(payload.toString())
})
```

To me the expected behavior is to either correct the `content-length` automatically and not worry about it, or if we know there is a problem`throw` an error (or callback with one maybe)

**Comment by geek** [comment]
@xjamundx that looks like a programmer error that wreck could assert on, or at least specify that it timed out waiting for the rest of the payload to be added to the request.

**Comment by xjamundx** [comment]
@geek that's what I was thinking. I tried to sort through the `wreck` source code, but I'm fairly unfamiliar with it, so I wasn't able to do much there. 

Presumably there's some code that basically says keep streaming the data until we reach `conte-length` or something and it never makes it?

**Comment by hueniverse** [comment]
@geek Planning on doing something about this? Otherwise please close.
