### ISSUE TITLE
Request Denied Error

### ISSUE THREAD

**Issue by captainjackrana** [hapijs/wreck#179]
After updating to Wreck v10.0, I've been intermittently getting these error messages - 
```
Error: Response Error: Request denied
    at read (/home/deploy/bane/node_modules/wreck/lib/index.js:530:61)
    at finish (/home/deploy/bane/node_modules/wreck/lib/index.js:371:20)
    at wrapped (/home/deploy/bane/node_modules/hoek/lib/index.js:871:20)
    at onReaderFinish (/home/deploy/bane/node_modules/wreck/lib/index.js:421:16)
```
What is the reason for this error? I dont think its related to the target server denying the request since it used to work well earlier

**Comment by geek** [comment]
@captainjackrana in v10 there really wasn't a change to errors (https://github.com/hapijs/wreck/issues/150) what version did you upgrade from?

In v11 we started wrapping 400+ status code responses in a boom error object.  https://github.com/hapijs/wreck/issues/162

**Comment by captainjackrana** [comment]
Apologies, this was v12 that throws request denied errors.. However, i downgraded to v9 and those errors aren't appearing anymore

**Comment by hueniverse** [comment]
This error doesn't match the code generating it:
https://github.com/hapijs/wreck/blob/master/lib/index.js#L530
It is missing the status code. Where is this coming from?

**Comment by geek** [comment]
@captainjackrana any ideas on the status code not being present?

**Comment by csrl** [comment]
The status code in the error wasn't introduced until v12.2.0. 

12.1.0 is the only version that matches the line number and error format

https://github.com/hapijs/wreck/blob/v12.1.0/lib/index.js#L530

**Comment by geek** [comment]
Closing for now, feel free to reopen @captainjackrana if you can provide more steps to help reproduce.
