### ISSUE TITLE
concern event on global process

### ISSUE THREAD

**Issue by rook2pawn** [hapijs/wreck#187]
Having reviewed the discussion in #111 and looking now at the readme

```
const symbol = Symbol.for('wreck');
process[symbol].on('response', (err, details) => {

    if (err) {
      console.error(err);
    }
});
```
There's something that isn't quite right with this interface, 

1. There's automatic, no choice lock-in on where the event lives and where it will go 
2. the fact that it defaults writes to other areas of global space, by default
3. the use case while very useful, is something that can be expressed as boilerplate in the readme IF the request simply returns the request and response event.

Instead its very natural to allow the coder to decide where they'd like this event to go and where they'd like it to be accessed. This breaks not only scoping, but also the first rules of good practices by global pollution.

Imagine something along the lines of where the wreck request returns the event

`const evt = wreck.get(url, cb);
`
So the README.md could then look like this

```
const evt = wreck.get(url, cb);

// Now you can feel free to export, expose the request and response events on evt where you feel to do so

const symbol = Symbol.for('wreck');
process[symbol] = evt;
```

At the minimum, would you be open to an examination PR that explores the idea of returning the event on a request instead of breaking scoping rules by default? @arb

**Comment by geek** [comment]
This doesn't pollute globals and is using Symbols, which will avoid any conflicts. Therefore, this is a safe solution to the problem. 

The goal is to provide process wide hooks to wreck request events, which this does. There isn't a global pollution and `process` will never add/overwrite a custom symbol for wreck, so there aren't any upgrade/conflict concerns.

Thanks for the extra thought around the implementation.
