### ISSUE TITLE
Shouldn't request event emit request object?

### ISSUE THREAD

**Issue by tlivings** [hapijs/wreck#209]
I'd expect for the `request` event to include the created request object, not simply the `uri` and `options` (which also allows mutations of these `options` resulting in potential side effects).

Similar to the functionality of the `response` event.

This would allow for consistent instrumentation of both `request` and `response` objects (attaching event listenings for logging, etc).

Instead, the only way to get at it today is through the promise's `req` property which doesn't feel ideal (but probably workable).

**Comment by hueniverse** [comment]
A year later, is this going to happen? If not please close.

**Comment by tlivings** [comment]
I’ll open a PR. We worked around it but I think this would still make a lot of sense.

**Comment by tlivings** [comment]
It is a simple enbough change but there seems to be a desire, indicated by the testing, to allow mutation of the `uri` argument prior to creating the request.

If this is a still a requirement, then I'll introduce another event prior to the request creation, and modify the `request` event to pass the created request.

Thoughts?

**Comment by tlivings** [comment]
Ok I can just submit the PR this weekend and let @geek see what he thinks.

**Comment by geek** [comment]
@tlivings the problem is that the request isn't created until after this event fires (https://github.com/hapijs/wreck/blob/master/lib/index.js#L186-L191). Another option is to add a new event: `onPostRequest` (mirrored from the hapi event names). We probably will need to add pre events though if we go that route, which is probably a good direction to make it clear when the event fires.

**Comment by tlivings** [comment]
The above PR introduces a new `preRequest` event and changes the `request` event. If you'd like me to instead use a `postRequest` event to avoid the breaking change, let me know. This just seemed to be more semantically correct to me.
