### ISSUE TITLE
Request phase timings

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/wreck#210]
I was curious if there was a suggestion on how to gather the request phase timings per Wreck call? 

If there isn't a currently suggested way to do this, is there an appetite for a PR adding this functionality?

```js
{
    wait,
    dns,
    tcp,
    firstByte,
    download,
    total
}
```

**Comment by geek** [comment]
There are a couple of options for taking these measurements. 
1. Use the wreck events for [request and response](https://github.com/hapijs/wreck#events) to calculate the timings
2. Create a custom [Agent class](https://nodejs.org/api/http.html#http_class_http_agent) and pass that to wreck in the options. The advantage with this approach is the new module should be reusable in other clients as well.

I do like the idea of adding these calculations, but I'm not sure most people will want or use them. Therefore, I'd rather see them introduced as an external module that integrates well with wreck. That being said, if you see any shortcomings in the events or agents required to support this functionality please open an issue and I'll be happy to fix.

**Comment by lostthetrail** [comment]
@geek Can you elaborate on the custom agent? I am not aware of a way to get a ref on the ClientRequest object from an Agent.

**Comment by geek** [comment]
@lostthetrail With the agent you have access to the sockets, which should provide most of the information
