### ISSUE TITLE
Stack trace lost during exception in latest Wreck

### ISSUE THREAD

**Issue by lostthetrail** [hapijs/wreck#211]
UPDATE: The problem below is a fundamental issue with `async/await`, the purpose of the issue is to see if we can find a way to resolve it in the wreck library.

When a Wreck call throws an exception, the error returned has an incomplete stack.

See below for the example code and output.

```
$ node .
Error: Response Error: 500 Internal Server Error
    at internals.Client._shortcut (.../wreck-async-await-stacktrace/node_modules/wreck/lib/index.js:593:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

REL: [https://github.com/lostthetrail/wreck-async-await-stacktrace/tree/master](https://github.com/lostthetrail/wreck-async-await-stacktrace/tree/master)

I am investigating this, but if someone sees this issue and know the issue, feel free to give me a heads up.

_Node v8.9.1_

**Comment by lostthetrail** [comment]
It appears related to:
https://github.com/nodejs/node/issues/11865

So this may be less a problem with Wreck and more with Node debugging/performance balance.

**Comment by geek** [comment]
@lostthetrail this is definitely an issue with how promises were designed and implemented. I'm open to any fixes in wreck to improve the debugging experience though

**Comment by lostthetrail** [comment]
@geek Does this same "missing stack" issue happen with Wreck prior to the async/await changes? I didn't think it did...?

**Comment by geek** [comment]
It didn't. I haven't been hit by anything yet that I haven't been able to debug with the current version. In your example at https://github.com/lostthetrail/wreck-async-await-stacktrace/blob/master/index.js#L18 you should use bounce... potentially rethrow. You are also able to log or throw a new error if you want a stack to locate where the request originated.

**Comment by lostthetrail** [comment]
@geek Agreed, one way to solve it will be to catch and wrap the error in a new error. The default behavior will leave people prone to arriving in production, getting an error and being unable to properly debug it.

Do you know if `hapi` already solved this, as it is using async/await all over the place?

**Comment by tlivings** [comment]
Because wreck makes shortcut functions (`get`, `post`, etc) wrap responses in errors when `statusCode` >= 400, I’d recommend instead just using `Wreck.request` method because you’re going to have a LOT less error cases within Wreck itself.

The fact is, if you have a response you do not have an error. The only promise rejections you should be receiving should be from timeouts, interrupted connections, etc.

In those cases you don't really need stack traces as much.

**Comment by lostthetrail** [comment]
This isn't really just a Wreck issue. My primary concern is with developer expectations. Most people would not assume that the stack traces they will get back using the latest version of Wreck will be reduced past usefulness.

**Comment by geek** [comment]
@lostthetrail promises also break postmortem debugging... fortunately, there are efforts to fix this in core.

In hapi I've migrated to async/await by using [bounce](https://www.npmjs.com/package/bounce), increased my error logging, and improved my error object interrogation. 

@tlivings you can check the error type and response status code to determine how to handle the error. But if you don't like that behavior keep using the `request` function, I won't change that one :)

**Comment by tlivings** [comment]
TIL about `bounce` — nice!

@geek yes, aware — thanks.
