### ISSUE TITLE
Stringified payload support

### ISSUE THREAD

**Issue by kanongil** [hapijs/wreck#212]
Currently the returned payload is a buffer. Similar to how the `json` option enables it to be parsed into an object, I would like an option for parsing it to a string.

This is not as simple as `payload.toString()`, which can fail non-utf8 charsets. Essentially wreck should extract a `charset` from the `content-type` header, and return `payload.toString(charset)`.

**Comment by hueniverse** [comment]
Seems like a reasonable option to add.

**Comment by hueniverse** [comment]
Is no one wants to work on this, let's close it.
