### ISSUE TITLE
Empty response handling

### ISSUE THREAD

**Issue by dominykas** [hapijs/wreck#220]
History: https://github.com/hapijs/nes/issues/106

I ran some tests (https://gist.github.com/dominykas/bfdfea6d10c1bc56b2c1fffc3074d70c) and found that Wreck handles empty responses slightly differently to Nes. Not that it's a big deal, but should

* empty response with no content-type be returned as `null` when `{ json: true }`
* empty response with `text/plain` content-type be returned as `null` when `{ json: true }`?

I guess in the first case, Nes treats `null` and `''` responses without content-type differently because it hooks directly into Hapi - there's no such distinction in http, but for the `text/plain` case - should it even attempt to parse as JSON at all?

**Comment by dominykas** [comment]
Related: https://github.com/hapijs/hapi/issues/3782

Should similar logic apply in Wreck? i.e. because it does not bother parsing `text/html` non-empty strings, it should not bother parsing _empty_ `text/html` / `text/plain` strings?

**Comment by hueniverse** [comment]
What's the state of things now? I've lost track.

**Comment by dominykas** [comment]
Just retested with latest published nes/hapi/wreck.

When calling wreck with `{ json: true }`, if the response body is empty, Wreck will return a `null` regardless of `content-type` header.

This probably makes sense when there is no content-type header at all (e.g. a 204 response from hapi), but I'm not sure it makes sense for a 200 response with a `content-type: text/*` - Wreck does not parse the non-empty body for `content-type: text/*` - it should return an empty string (buffer)?

**Comment by hueniverse** [comment]
Non JSON based data should not be parsed.
