### ISSUE TITLE
Investigate only piping the payload after a connection is established

### ISSUE THREAD

**Issue by geek** [hapijs/wreck#222]
Relates to https://github.com/hapijs/wreck/blob/576ce9de0231de2d419f4e965f6bc70afe203609/lib/index.js#L303-L322

**Comment by ggoodman** [comment]
When passing a readable stream as `options.payload`, the readable stream will be piped to the `ClientRequest` before a socket connection is established. That causes the stream to be put into the flowing mode meaning that the stream cannot be re-used in the event that no socket connection can be established.

Our work-around has been to pass a `stream.PassThrough` instance as `options.payload` and then to pipe the actual payload into the pass-through stream once a socket connection is established (`'connect' event on the socket).
