### ISSUE TITLE
[Question] Response Streams

### ISSUE THREAD

**Issue by petermikitsh** [hapijs/wreck#237]
As discussed in https://github.com/hapijs/wreck/issues/153, in prior versions of Wreck (<=12.5), if you wanted to stream the response, you could do as follows:

```js
Wreck.request('GET', 'https://github.com/hapijs/wreck', {}, (err, res) => {
  res.pipe(process.stdout)
})
```

However, in v13 (with the migration to the Promise-based API), the callback function (4th function argument above) was removed.

Is it possible to access the **un-used** stream (e.g., so it can be piped) in the latest version of wreck?

I was looking at the following in the README, but I'm unsure what to make of it:

For `request()` - https://github.com/hapijs/wreck#requestmethod-uri-options:

```
Returns a promise that resolves into a node response object. The promise has a req property which is the instance of the node.js ClientRequest object.
```

For `get()` - https://github.com/hapijs/wreck#geturi-options:

```
Returns a promise that resolves into an object with the following properties: - res - The HTTP Incoming Message object, which is a readable stream that has "ended" and contains no more data to read.
```

**Comment by geek** [comment]
@petermikitsh you are able to use the response from the call to `Wreck.request` to pipe. Here is how that can look:

```js
const Wreck = require('wreck');

async function main() {
  const res = await Wreck.request('get', 'https://google.com');
  res.pipe(process.stdout);
}

main();
```

If you plan to use one of the shortcut methods you won't have the pipe option, but you can write out the buffered response payload like the following:

```js
const Wreck = require('wreck');

async function main() {
  const res = await Wreck.get('https://google.com');
  process.stdout.write(res.payload.toString());
}

main();
```

I hope this helps, let me know if you have any other questions.

**Comment by petermikitsh** [comment]
Tried it out, and this worked. Thank you, that was helpful! My example code:

```
const Wreck = require('wreck');
const express = require('express');

const app = express();

app.get('/', (req, res) => {
  setTimeout(() => {
    res.write('<!DOCTYPE html>');
    res.write('hello world 1000ms\r\n');
  }, 1000);

  setTimeout(() => {
    res.write('hello world 3000ms\r\n');
  }, 3000);

  setTimeout(() => {
    res.write('hello world 5000ms\r\n');
    res.end();
  }, 5000);
});

app.get('/test', async (req, res) => {
  const stream = await Wreck.request('get', 'http://0.0.0.0:3000/');
  stream.pipe(res);
});

app.listen(3000);
```

**Comment by geek** [comment]
@petermikitsh glad to hear it!
