### ISSUE TITLE
Can Wreck parse urls with the WHATWG Url?

### ISSUE THREAD

**Issue by WesTyler** [hapijs/wreck#238]
It looks like Wreck is not using the WHATWG Url parser for Node.js [here](https://github.com/hapijs/wreck/blob/master/lib/index.js#L66) that hapi recently [moved to](https://github.com/hapijs/hapi/blob/master/lib/request.js#L137). WHATWG Url is also the default for Node.js beginning in the 11.x release line.

I'll open up a PR in just a few minutes, just wanted to create an issue for tracking.

**Comment by WesTyler** [comment]
Turns out Wreck was using the resulting Url object from `Url.parse` as a vehicle for additional request options like `agent`, `headers`, etc. The `Url.URL` class does not support those additional fields.

I'm working on trying to implement a strategy for merging the URL instance properties with the currently-expected options in order to maintain the contract with the Wreck events. If that proves unsuccessful this may end up being a breaking change 😬 :(

**Comment by geek** [comment]
Fixed by https://github.com/hapijs/wreck/pull/239
