### ISSUE TITLE
Change redirect method in `beforeRedirect`

### ISSUE THREAD

**Issue by delaguilaluis** [hapijs/wreck#248]
Hi! Since Wreck 11, 301 and 302  HTTP code redirects would be issued with the same method than the original request. I want to change the method from `POST` to `GET`, but I wasn't able to do it through the `beforeRedirect` function in Wreck's options. I know `beforeRedirect` allows you to change the request options by changing its `requestOptions` parameter, but that set of options does not include `method` or `uri`.

Before detecting a redirect (probably using the `redirected` function), and then manually issuing a new request with the method I desire, I would like to know if I'm missing any configuration/method in Wreck than would allow me to say "I want 301 redirects method to be changed to GET" (as in Wreck < 11).

Thanks!

**Comment by hueniverse** [comment]
What changed in version 11 that broke this capability?

**Comment by delaguilaluis** [comment]
What changed is that methods of a redirected request (301 and 302) no longer change the method to `GET`(consequence of solving the issue #138), which happens to be what I need. I don't think the capability to change the method of a redirect existed before.
