### ISSUE TITLE
Default Query Params

### ISSUE THREAD

**Issue by flipxfx** [hapijs/wreck#249]
Is there a suggested way to have default query parameters? We have an API that we use that requires the API token to be in the query parameters for each call 😢

**Comment by geek** [comment]
You can use the `defaults` function to setup a wreck instance that you reuse for different requests.

```js
const wreck = Wreck.defaults({
  baseUrl: 'http://somesite.com?with=param
});
```

However, under the covers it uses `new Url.URL(path, baseUrl)` which will overwrite the querystring parameters if path has a truthy value, so if you request an empty string path you'll be fine and retain the querystring.

**Comment by flipxfx** [comment]
Yeah, our issue is that that we need something like:

```js
const wreck = Wreck.defaults({
  baseUrl: 'http://somesite.com?apikey=123'
});

wreck.get('/users?limit=500')
```

We need the query params to have `limit` and `apikey`.

I've tried messing with using `preRequest` to add the query parameter but no luck.

```js
const wreck = Wreck.defaults({
  baseUrl: 'http://somesite.com'
});

wreck.events.on('preRequest', (uri, options) => {
  uri.searchParams.append('apikey', '123')
})

wreck.get('/users?limit=500')
```

**Comment by flipxfx** [comment]
Looking at the source code I think I know why my `preRequest` workaround isn't working.

It looks like I misunderstood what `uri` from `preRequest` is. I thought is was an instance of `URL` but it's not? 

And also probably because it's a asynchronous event 🤷‍♂

**Comment by flipxfx** [comment]
I think I got it! But yeah it is a little confusing and maybe an example of how to use `preRequest` to change the URL would be helpful 😄 

```js
wreck.events.on('preRequest', (uri, options) => {
  const url = new URL(uri.href)
  url.searchParams.append('source', 'schumacher')

  uri.path = `${url.pathname}${url.search || ''}`
})
```
