### ISSUE TITLE
Even Loop Lag while parsing large JSON payloads

### ISSUE THREAD

**Issue by codeburke** [hapijs/wreck#251]
We have an issue where we receive some sizable JSON payloads (~500kB). What we've found is that the underlying `JSON.parse` is the cause of these event loop lag spikes. We are testing a workaround now in our own `wreck`-wrapping http library you use an async JSON parser ([yieldable-json](https://www.npmjs.com/package/yieldable-json)) in order to keep the event loop lag consistent regardless of the size of the JSON being parsed. I wanted to drop an issue here to see if the maintainers feel like this would be a good feature addition directly to `wreck`. If so, and assuming the testing proves to be beneficial, then I could work on a PR to add it in.

**Comment by geek** [comment]
@codeburke thank you for raising this. Looking at the yieldable-json module shows that the github version has received a few commits, however, those commits haven't made it to the published version in 2 years, which is a little worrisome. 

One of the nice things about wreck is that you can very simply create a wrapping layer with custom helper methods for `get`, `post`... like we are doing in the module and use a custom parser. Hopefully this will workaround the issue that you are experiencing related to large payload parsing.
