### ISSUE TITLE
How to get js file from cdn?

### ISSUE THREAD

**Issue by srigar** [hapijs/wreck#257]
Hey, Currently we are using wreck in our application. In hapijs handler, we are trying to access the js file by the help of wreck. But we are getting the below error and code snippet given below,

`
        method: 'GET',
        path: '/workbox-sw.js',
        handler: async (req, res) => {
            const response = await Wreck.request('get', 'https://dev.cdn.com/0.2.3/sw.js');
            return res.file(response);
        }
`

<img width="662" alt="Screenshot 2019-09-11 at 10 29 51 PM" src="https://user-images.githubusercontent.com/20384652/64718440-d0f6a300-d4e3-11e9-8463-b22cb27b49dd.png">

**Comment by Nargonath** [comment]
What is the content of `response`? Have you checked it?

**Comment by hueniverse** [comment]
This doesn't make any sense. You are taking the result of an HTTP request (buffer) and passing it to what I assume to be inert's `file` handler extension which expects a file name. If the file is local, just pass the path to `re.file()`. If the file is remote, use wreck and then just return the response as-is.
