### ISSUE TITLE
Boom.Boom() is not a constructor when installed with yarn

### ISSUE THREAD

**Issue by spanditcaa** [hapijs/wreck#268]
#### Support plan

* *which support plan is this issue covered by?* Legacy/Patreon
* *is this issue currently blocking your project?* yes
* *is this issue affecting a production system?* yes

#### Context

* *node version*: 13.4
* *module version with issue*: 16.0.1
* *last module version without issue*:  
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...):hapi application
* *any other relevant information*: yarn 1.21.1 - works as expected with npm 6.13.4

#### What are you trying to achieve or the steps to reproduce?

when the called server returns a 401 Unauthorized response, we see the following error:

```
Boom.Boom is not a constructor
TypeError: Boom.Boom is not a constructor
    at internals.Client._shortcut (/node_modules/@hapi/wreck/lib/index.js:557:15)
```

#### What was the result you got?

Boom.Boom is not a constructor

#### What result did you expect?

```
Response Error: 401 Unauthorized
Error: Response Error: 401 Unauthorized
    at internals.Client._shortcut (/node_modules/@hapi/wreck/lib/index.js:557:15)
```

This can be resolved by changing https://github.com/hapijs/wreck/blob/50c924bfda39c375073d5625a22b426c2714d2cc/lib/index.js#L556 to:

```
throw new Boom(`Response Error: ${res.statusCode} ${res.statusMessage}`, { statusCode: res.statusCode, data });
```

**Comment by hueniverse** [comment]
Can you show me you `npm ls` result? Looks like wrong version of boom being used by wreck.

**Comment by spanditcaa** [comment]
@hueniverse this appears to be an issue with package resolution for @hapijs/wreck when using yarn 1.21.1 (latest as of 12/20/19).  The project that has this issue uses yarn, not NPM.  I noticed a ```yarn list``` did not show @hapijs/boom as a dependency of @hapijs/wreck.  I nuked the yarn.lock for this project and reinstalled with NPM, and wreck/boom work as expected.

**Comment by spanditcaa** [comment]
scratch the above -- @hueniverse I then deleted node_modules again (plus package-lock) and reinstalled with yarn, and that works as well.  Something was off in our dependencies/lockfiles - as we did see this from multiple computers.

Closing.  Thanks.
