### ISSUE TITLE
Question: Always returning 502 for client request errors?

### ISSUE THREAD

**Issue by tuckbick** [hapijs/wreck#273]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: n/a
* *module version*: latest
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application and https://github.com/ExpediaGroup/service-client
* *any other relevant information*: 

#### How can we help?

I am curious about the rational behind always returning a 502 (bad gateway error) response when there is a client request error. If there is no firm rational, would you be open to a PR to propagate the underlying error code?

Once the error is finally thrown from Wreck, it looks something like below. Note the differing error codes.
```json
{
  "name": "connectTimeout",
  "code": "ETIMEDOUT",
  "statusCode": 504,
  "trace": [
    {
      "method": "GET",
      "url": "http://localhost:8080/timeout"
    }
  ],
  "isBoom": true,
  "isServer": true,
  "data": null,
  "output": {
    "statusCode": 502,
    "payload": {
      "message": "Client request error: Socket connect timeout.",
      "statusCode": 502,
      "error": "Bad Gateway"
    },
    "headers": {}
  }
}
```

Code in question: https://github.com/hapijs/wreck/blob/923f1899a63676fb167b1794bb75a9527666263c/lib/index.js#L188-L192

**Comment by hueniverse** [comment]
Since when does node client error set status code?

**Comment by tuckbick** [comment]
In the code quoted above, `Boom.badGateway()` is used and sets a status code, yeah?

**Comment by hueniverse** [comment]
In your example you show a 504 status code. Where is that coming from?
