### ISSUE TITLE
memory leak fix are erases

### ISSUE THREAD

**Issue by Bodasia** [hapijs/wreck#274]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: 8.17
* *module version with issue*: 17.0.0
* *last module version without issue*: 15.1
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: https://github.com/hapijs/wreck/commit/2faa87d7153a9915938da33ed454775f0008e57e this commit erases fix of memory leak https://github.com/hapijs/wreck/pull/250

#### What was the result you got?
memory leak

#### What result did you expect?
absence memory leak

**Comment by kanongil** [comment]
Did you really test with v17? The `abort` property is no longer assigned with 61754536e8264a4119f5200d29eb2ae70239ac0b.
