### ISSUE TITLE
CHANGELOG not updated for 17.0.1

### ISSUE THREAD

**Issue by abeluck** [hapijs/wreck#286]
#### Context

* *node version*: 14
* *module version*: 17.0.0 -> 17.0.1

#### What are you trying to achieve or the steps to reproduce ?

I see on npm that 17.0.1 is available, but it doesn't appear in the changelog: https://hapi.dev/module/wreck/changelog/

Eran was very meticulous about keeping documentation and the changelog up to date. I'd hate to see that slip now!

**Comment by abeluck** [comment]
I went to go submit a PR for the changelog, but I can't find it. Where is the code for https://hapi.dev/family/wreck/changelog/ ?

**Comment by lloydbenson** [comment]
The changelog gets auto generated every time the website gets built. This should happen pretty soon (we getting some other prs done for the website) but the website does lag a little so please be patient. I confirmed that the changelog will show 17.1.0 (I think thats what you meant) the next time it is built. If you aren't aware the site is statically generated.

**Comment by abeluck** [comment]
17.1.0 yes, sorry.

Thanks @lloydbenson I assumed the project pages were somehow directly connected to this git repo. My error, sorry for the noise. Many thanks!

**Comment by lloydbenson** [comment]
When the site looks up all the information for all the modules it does eat up many resources for build times and github api key calls so we can't run the website on every commit.
