### ISSUE TITLE
hapi/wreck error

### ISSUE THREAD

**Issue by vinaykumar612** [hapijs/wreck#289]
#### Support plan

* *is this issue currently blocking your project?* (yes/no):no
* *is this issue affecting a production system?* (yes/no):no

#### Context

* *node version*: *14.17.5*
* *module version*: *17.1.0*
* *environment* *Node* 
* *used with* :*Nodejs*
* *issue with hapi/wreck module getting Client request error: unable to verify the first certificate*:

#### How can we help?
*I'm using hapi/wreck module to call secured api(https) method is POST.
Getting Client request error: unable to verify the first certificate error.
I'm currently using below config in agents. please do suggest If I'm using the incorrect one.*
```js
agents: {
    httpsAllowUnauthorized: new Https.Agent({ rejectUnauthorized: false })
}
```

**Comment by vinaykumar612** [comment]
*Hi @devinivy Still getting same error, added my configurations below*

```js
const callCvs = async _ => {
  try {
const method = 'POST';
const uri = '/**';
var config = {
  baseUrl: '**.com',
  headers: { 
    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 
    'Accept-Charset': 'UTF-8', 
    'X-HP-SBS-ApplicationId': '**', 
    'X-HP-SBS-ApplicationKey': '**', 
    'X-HP-SBS-SessionContext': '**', 
    'X-HP-SBS-TestRequest': 'false', 
    'X-HP-SBS-ApplicationEPRId': '**', 
    'timeout': '1'
  },
  payload : data,
};
const response=await Wreck.request(method, uri,config, { rejectUnauthorized: false });
    return response.data;
  } catch (error) {
    message = error.message;
    console.log(error.message);
    return message;
  }
};
```

**Comment by vinaykumar612** [comment]
*Hi @kanongil Thanks for correction.
Modified accordingly as suggested and below is the modified config.
Still getting **authorizationError: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'***

```js
const callApi = async _ => {
  try {
const method = 'POST';
const uri = '/**';
var config = {
  baseUrl: '**.com',
  headers: { 
    'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 
    'Accept-Charset': 'UTF-8', 
    'X-HP-SBS-ApplicationId': '**', 
    'X-HP-SBS-ApplicationKey': '**', 
    'X-HP-SBS-SessionContext': '**', 
    'X-HP-SBS-TestRequest': 'false', 
    'X-HP-SBS-ApplicationEPRId': '**', 
    'timeout': '1'
  },
  timeout: 15000,
  payload : data,
  rejectUnauthorized:false,
  agent: null
};
const response=await Wreck.request(method, uri,config);
console.log(response);
    return response.data;
  } catch (error) {
    message = error.message;
    console.log(error.message);
    return message;
  }
};
```

*Please share the rules need to be followed to use hapi/wreck*

**Comment by devinivy** [comment]
I ran your code with the same version of wreck and nodejs, and I was not able to reproduce the issue.  In the logged output I do see `authorizationError: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'` as you mentioned, but it doesn't come from a thrown error.  Instead, it is just a property on `response.socket` from the `console.log(response)`.  If I remove the configuration `rejectUnauthorized: false` then it is actually thrown as an error with the message `unable to verify the first certificate`.  If we're seeing the same thing, then I think this is the expected and correct behavior 👍

**Comment by vinaykumar612** [comment]
*Thanks team for you help.*
*Everything is fine except below two lines*
*After adding below two lines of code Its working as expected*
```js
const body = await Wreck.read(response, config);
const resString=body.toString();
```
*Hence closing the issue.*
