### ISSUE TITLE
How to pass https proxy information in the config?

### ISSUE THREAD

**Issue by vinaykumar612** [hapijs/wreck#290]
#### Support plan

* *is this issue currently blocking your project?* (yes):
* *is this issue affecting a production system?* (no):

#### Context

* *node version*: v14.17.5
* *module version*: 17.1.0
* *environment* : node
* *used with* enterprise nodejs framework:
* *any other relevant information*:

#### How can we help?

*I need to pass https Proxy url in the config. Please help me to add.*

```js
const some = 'properly formatted code example';
```js
const config={
        baseUrl:'https://my.salesforce.com',
        headers:{
            'Content-Type':'application/x-www-form-urlencoded'
        },
        timeout:15000,
        payload:data,
        rejectUnauthorized: false,
    }
```

**Comment by devinivy** [comment]
I'd like to help, but I am not sure that I understand your issue.  Are you trying to set `x-forwarded-for`, `x-forwarded-port`, `x-forwarded-host`, and `x-forwarded-proto` headers?  If so, here's an example of how hapi's proxy h2o2 sets those wreck options: https://github.com/hapijs/h2o2/blob/3093ac11f9055a3d1adb0005e1f80c0ae5f479c9/lib/index.js#L138-L141

**Comment by vinaykumar612** [comment]
Thanks @devinivy .
My Question is 
I have a proxy looks like

```js
const proxy='http://web-proxy.***corp.net:8080';
```
and I want to use that proxy in below config.
```js
const config={
        baseUrl:'https://hp--TEST.my.salesforce.com',
        headers:{
            'Content-Type':'application/x-www-form-urlencoded'
        },
        timeout:15000,
        payload:data,
        rejectUnauthorized: false,
    }
```
What is the option key name that I can use inside the config.
Example:  proxy:'http://web-proxy.***corp.net:8080',

**Comment by Nargonath** [comment]
I'm not sure I understand your problem either. Do you want to actually call two different URL at the same time? Otherwise why not just replace your `baseUrl` with your `proxy` URL if you want to go through your proxy?

**Comment by vinaykumar612** [comment]
I would like to call one URL only
i.e., 
```js
https://TEST.my.salesforce.com/services/oauth2/token
```
As it is a secured API I need to pass the proxy information as well.

My question here is how to pass that proxy information in wreck.
i.e.,
```js
host:web-proxy.***corp.net
port:8080
```

**Comment by Nargonath** [comment]
I'm not sure you can achieve that with `wreck`. It doesn't have a proxy feature as [`request`](https://github.com/request/request#proxies) did for example.
