### ISSUE TITLE
Add certificate options for requests

### ISSUE THREAD

**Issue by geek** [hapijs/wreck#66]
See https://github.com/hapijs/hapi/issues/2070

**Comment by achingbrain** [comment]
I'm trying to convert some code that uses [request](https://libraries.io/npm/request) to Wreck to take advantage of the [good](https://libraries.io/npm/good) integration. The service we are talking too needs client certificates sent so this would be super useful.

**Comment by achingbrain** [comment]
For anyone else with the same problem, I managed to specify client certificates by overriding Wreck's default https agent:

```javascript
var Wreck = require('wreck');
var https = require('https');

Wreck.agents.https = new https.Agent({
  cert: ...,
  key: ...,
  ca: ...,
  ...
});

// now make a request as usual
Wreck.request('GET', 'https://...', ...);
```

Wreck is a singleton so these options will be applied to all outgoing requests no matter where you `require` Wreck from.

If I wanted to vary the certs on a per-request basis I could probably have also done it by passing an agent to the request method as part of the options:

```javascript
Wreck.request('GET', 'https://...', {
  agent: new https.Agent({
    ...
  });
}, ...);
```

**Comment by kanongil** [comment]
You could use the new `defaults()` method to handle this, avoiding interference of other modules `wreck` usage. Eg.:
```js
var wreck = Wreck.defaults({ agent: agent });
wreck.request(…);
```

Note that this will fail until #93 is resolved, if you use redirects.

**Comment by nlf** [comment]
sounds like this can probably be documented and closed?
