### ISSUE TITLE
Add logging to req/res details for debug mode

### ISSUE THREAD

**Issue by geek** [hapijs/wreck#72]
To make it easier to debug issues, we should add a log option for req/res details, along with response times.  This should be logged to stdout or if the debug environment variable indicates, to a file.

**Comment by danielb2** [comment]
I'm working on this

**Comment by hueniverse** [comment]
Can we somehow share this config with good? Can someone propose a way to do this globally?

**Comment by kevinmstephens** [comment]
It would be great if the event emitter were exposed so that someone could register a listener and then pass it to good via `request.log` or `server.log`.
