### ISSUE TITLE
Read automatically converts payload from Buffer to UTF-8 String

### ISSUE THREAD

**Issue by christophercliff** [hapijs/wreck#75]
This causes problems when doing a `GET` on a binary file. Curious why not leave the payload as a Buffer?

**Comment by Marsup** [comment]
Looking at the code a bit, it's not doing that, unless the content-type is saying it can.
https://github.com/hapijs/wreck/blob/master/lib/index.js#L257
Unless you're forcing json (L247) or the response is application/json, it shouldn't do that.

**Comment by christophercliff** [comment]
This block: https://github.com/hapijs/wreck/blob/12011cd59c256fd6df2718d93ebd9a46a970382c/lib/index.js#L397-L399

Looks like it was introduced [here](https://github.com/hapijs/wreck/commit/dd6661ced599f0a279dda362845284a26af906ca#diff-6d186b954a58d5bb740f73d84fe39073R389) and [here](https://github.com/hapijs/wreck/commit/fd43b860bf26d6db04d3544a6de7c3ee1097813a#diff-6d186b954a58d5bb740f73d84fe39073R389), although not clear why.

**Comment by christophercliff** [comment]
Adding @cjihrig

**Comment by cjihrig** [comment]
I can't remember why I added the `if (payload instanceof Buffer)`, but if you look at the diff from #6, `payload.toString()` was being called unconditionally before that. FWIW, all the tests still pass if that `if` statement is removed, although it would represent a breaking change.

**Comment by christophercliff** [comment]
From the README:

> The payload in the form of a Buffer or (optionally) parsed JavaScript object (JSON).

So this is a bugfix, no?

**Comment by grinnellian** [comment]
Also having binary file `GETS` fail:
```
var uri = "https://phs.googlecode.com/files/Download%20File%20Test.zip";

var options = {};
options.headers = {
  Accept: "application/x-zip-compressed"
};

Wreck.get(uri, options, function (err, response, payload) {
  if (err) throw err;
  if (!Buffer.isBuffer(payload)) throw new Error("Payload is not a buffer”);
  console.log(“So far so good”);
});
```
