### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by chanakyap** [hapijs/wreck#80]
I am trying to add api version number to all my responses from the API. 
All responses from my API are JavaScript objects like,
 reply({user:{name: 'foo',email: 'bar@foo.com'}});

So i am doing this to get my desired result.

```javascript
server.ext('onPreResponse', function (request, reply) {
    var response = request.response;
    if(!response.isBoom){
      Wreck.read(response, {json: true}, function (err, body) {
        body.version = 'api_version #0.1#';
        body.copyright = 'copyright';
        body.timestamp = Date.now();
        reply(body);
      });
    }else{
      reply.continue();
    }
  });
```
But it throws and error , 
Debug: internal, implementation, error 
    TypeError: Uncaught error: undefined is not a function
    at internals.Client.read (/home/codeBase/forked_repo/gro-api/node_modules/wreck/lib/index.js:315:9)
    at /home/codeBase/forked_repo/gro-api/server.js:61:13
    at /home/codeBase/forked_repo/gro-api/node_modules/hapi/lib/handler.js:312:22
    at iterate (/home/codeBase/forked_repo/gro-api/node_modules/hapi/node_modules/items/lib/index.js:35:13)
    at done (/home/codeBase/forked_repo/gro-api/node_modules/hapi/node_modules/items/lib/index.js:27:25)
    at Function.wrapped (/home/codeBase/forked_repo/gro-api/node_modules/hapi/node_modules/hoek/lib/index.js:813:20)
    at Function.internals.continue (/home/codeBase/forked_repo/gro-api/node_modules/hapi/lib/reply.js:102:10)
    at /home/codeBase/forked_repo/gro-api/node_modules/hapi-i18n/index.js:43:26
    at /home/codeBase/forked_repo/gro-api/node_modules/hapi/lib/handler.js:312:22
    at iterate (/home/codeBase/forked_repo/gro-api/node_modules/hapi/node_modules/items/lib/index.js:35:13)

Any idea where i am going wrong?

**Comment by Marsup** [comment]
`request.response` is not a stream, it's a response object, you probably want `request.raw.res`.

**Comment by chanakyap** [comment]
By using request.raw.res, callback passed to wreck.read is not getting called.

**Comment by geek** [comment]
@chanakyap you will want to check the `request.response.variety` and depending on the type process it differently. So for a stream you can use your above method...

**Comment by chanakyap** [comment]
@geek request.response.variety is 'plain', is wreck unnecessary here and i can directly manipulate response here?

**Comment by geek** [comment]
@chanakyap in that case you don't need wreck to read the response.  Since you closed it, does that mean you got it working?

**Comment by chanakyap** [comment]
@geek yeah i got it working with out using wreck, i have referenced another issue i posted regarding same, and it has the solution, if anyone wants to take a look. Thanks for the help.
