### ISSUE TITLE
Change "response" Payload

### ISSUE THREAD

**Issue by arb** [hapijs/wreck#83]
I propose we change the payload we send to "response" handlers to be `err, payload` and just make `payload` a single large object rather than the five parameters we are currently passing. Much easier to maintain and won't introduce breaking changes when we need to add more to it.

**Comment by geek** [comment]
you mean the response event?  

I am fine with `(err, details)`, `payload` wouldn't be very useful

**Comment by arb** [comment]
The value send back when we do `emit(err,.....)` it doesn't matter what we call it, just something that's a big single object rather than a bunch of little arguments. I can see why `payload` would be confusing though in retrospect :smile:

**Comment by hueniverse** [comment]
What line of code specifically?

**Comment by arb** [comment]
https://github.com/hapijs/wreck/blob/master/lib/index.js#L103

**Comment by hueniverse** [comment]
Oh, the event stuff. I could not care less. I hate using event interfaces. They suck.

**Comment by arb** [comment]
Care to elaborate on that? I'd be interested in hearing about alternate approaches.

**Comment by nlf** [comment]
nudge nudge @geek is this something you intend to implement? if not, let's close it
