### ISSUE TITLE
payload from callback param is empty

### ISSUE THREAD

**Issue by kswedberg** [hapijs/wreck#90]
When sending a POST with `options.payload` as a stringified JSON object, I get an empty string from the `payload` parameter of the callback function. If I add `json: true` or `json: 'force'` to the options object, I get `null` for the callback. I tried to track down where things are breaking in wreck/lib/index.js, and it looks like there might be something up with the Recorder instance. I can't see where its _write method is being called, and the buffer returned by `reader.collect()` always has a length of 0, even though in that same function I can still see the options.payload JSON. 

Am I doing something wrong here? Or is there a bug? Let me know if you need any more information. I would love to be able to use this plugin with my new hapi project.

Thanks.

**Comment by arb** [comment]
Can you post some code?

**Comment by kswedberg** [comment]
You know, I think it's actually a problem on my end with db setup so the route isn't returning anything. Sorry for the hassle.
