### ISSUE TITLE
Module for progress reporter

### ISSUE THREAD

**Issue by thegoleffect** [hapijs/wreck#98]
something like https://www.npmjs.com/package/request-progress

**Comment by thegoleffect** [comment]
I can't add feature request label.

**Comment by nlf** [comment]
is this still needed? i feel like this could be implemented by piping a stream response from wreck through a third party module and it wouldn't require any changes to wreck itself. seems like demand is small enough (judging by the nearly 2 year old issue) to close this one if that's the case.
